apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "" # create gmail account, enable 2fa, create an app password. Dont push credentials to github ;)
  GMAIL_PASSWORD: ""
type: Opaque
